name: simple_gql_example
description: A minimal library to do GraphQL queries and mutations (subscriptions not handled yet)
version: 1.1.1
homepage: https://github.com/lecuivre-alban/simple_gql

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  simple_gql: 1.1.1
